metrics_job

diff --git a/.github/workflows/nodejs-blog-practica_workflow.yml b/.github/workflows/nodejs-blog-practica_workflow.yml
--- a/.github/workflows/nodejs-blog-practica_workflow.yml
+++ b/.github/workflows/nodejs-blog-practica_workflow.yml
@@ -215,12 +215,12 @@ jobs:
           plugin_languages_recent_load: 20
           plugin_languages_recent_days: 14
           filename: README.md
-          output_action: file
+          output_action: markdown-embed
           committer_token: ${{ secrets.PUSH_TOKEN }}
           # committer_branch: main
           # committer_message: "docs: updated GitHub metrics"
           # committer_repository: fmontesdev/fmontesdev
-          # config_output: markdown
+          config_output: markdown
 
       # Después de actualizar las métricas
       - name: Print README after metrics update
@@ -243,14 +243,15 @@ jobs:
           git status
           git diff README.md
           
-      - name: Commit and push changes
+      - name: Verify and commit changes
         run: |
+          if grep -q "No content available" README.md; then
+            echo "Error: Invalid content detected"
+            exit 1
+          fi
           git config --global user.email "f.montesdoria@gmail.com"
           git config --global user.name "fmontesdev"
-          cd $GITHUB_WORKSPACE
           git add README.md
           git status
           git commit -m "docs: updated metrics" || echo "No changes detected"
-          git remote -v
-          git branch
-          git push origin main -f || git push origin HEAD:main -f
+          git push origin main -f
