metrics_job

diff --git a/.github/workflows/nodejs-blog-practica_workflow.yml b/.github/workflows/nodejs-blog-practica_workflow.yml
--- a/.github/workflows/nodejs-blog-practica_workflow.yml
+++ b/.github/workflows/nodejs-blog-practica_workflow.yml
@@ -203,23 +203,23 @@ jobs:
       - name: Update metrics in README
         uses: lowlighter/metrics@latest
         with:
-          filename: github-metrics.svg
+          # filename: github-metrics.svg
           # PAT personal access token, diferente a GITHUB_TOKEN
           token: ${{ secrets.METRICS_TOKEN }}
           user: fmontesdev        
           template: classic
-          base: ""        
+          base: header, activity      
           config_timezone: Europe/Madrid
           plugin_languages: yes
           plugin_languages_sections: most-used
           plugin_languages_indepth: yes
           plugin_languages_recent_load: 20
           plugin_languages_recent_days: 14
-          # filename: metrics.svg
-          # output_action: file
-          # committer_token: ${{ secrets.PUSH_TOKEN }}
-          # committer_branch: main
-          # committer_message: "docs: updated GitHub metrics"
+          filename: README.md
+          output_action: commit
+          committer_token: ${{ secrets.PUSH_TOKEN }}
+          committer_branch: main
+          committer_message: "docs: updated GitHub metrics"
           # committer_repository: fmontesdev/fmontesdev
           # config_output: markdown
 
@@ -237,14 +237,14 @@ jobs:
       #     git commit -m "Añadidas métricas al README personal" || echo "No changes to commit"
       #     git push origin main --force
 
-      - name: Update README with metrics
-        run: |
-          echo "Updating README.md with metrics..."
-          awk '/## Resultados de Métricas/ {print; print "![Metrics](github-metrics.svg)"; next} 1' README.md > temp.md && mv temp.md README.md
-          git config --global user.email "f.montesdoria@gmail.com"
-          git config --global user.name "fmontesdev"
-          git add README.md
-          git commit -m "Update README.md with static GitHub metrics" || echo "No changes to commit"
-          git fetch origin main
-          git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping pull step")
-          git push origin main || echo "Push failed; skipping push"
+      # - name: Update README with metrics
+      #   run: |
+      #     echo "Updating README.md with metrics..."
+      #     awk '/## Resultados de Métricas/ {print; print "![Metrics](github-metrics.svg)"; next} 1' README.md > temp.md && mv temp.md README.md
+      #     git config --global user.email "f.montesdoria@gmail.com"
+      #     git config --global user.name "fmontesdev"
+      #     git add README.md
+      #     git commit -m "Update README.md with static GitHub metrics" || echo "No changes to commit"
+      #     git fetch origin main
+      #     git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping pull step")
+      #     git push origin main || echo "Push failed; skipping push"
