metrics_job

diff --git a/.github/workflows/nodejs-blog-practica_workflow.yml b/.github/workflows/nodejs-blog-practica_workflow.yml
--- a/.github/workflows/nodejs-blog-practica_workflow.yml
+++ b/.github/workflows/nodejs-blog-practica_workflow.yml
@@ -282,13 +282,13 @@ jobs:
           echo "README.md after replacement:"
           cat README.md
 
-      # - name: Commit and push updated README with markdown image
-      #   run: |
-      #     git config user.name "github-actions"
-      #     git config user.email "actions@github.com"
-      #     git add README.md
-      #     git commit -m "docs: updated README with GitHub metrics image" || echo "No changes to commit"
-      #     # Traemos los cambios remotos y los integramos (usando la estrategia "theirs" para resolver conflictos)
-      #     git pull --rebase --strategy-option=theirs
-      #     git push origin main || echo "Push failed; skipping push"
+      - name: Commit and push updated README with markdown image
+        run: |
+          git config user.name "github-actions"
+          git config user.email "actions@github.com"
+          git add README.md
+          git commit -m "docs: updated README with GitHub metrics image" || echo "No changes to commit"
+          # Traemos los cambios remotos y los integramos (usando la estrategia "theirs" para resolver conflictos)
+          git pull --rebase --strategy-option=theirs
+          git push origin main || echo "Push failed; skipping push"
 
